FROM ubuntu

RUN apt update
RUN apt install -y curl
RUN apt install -y jq

COPY download-frozen-image-v2.sh .
COPY archive.sh .

COPY bin/agent .

COPY certs/4be43aa6f1-certificate.pem.crt certs/
COPY certs/4be43aa6f1-private.pem.key certs/
COPY certs/AmazonRootCA1.pem certs/
COPY nodeconfig_secunet.json nodeconfig.json

CMD ["./agent", "-v", "--broker=tls://asnhp33z3nubs-ats.iot.us-east-1.amazonaws.com:8883", "--subClientId=nodes/awsdev", "--pubClientId=manager/awsdev", "--publish=status", "--heartbeat=100", "--loglevel=debug"]
