FROM ubuntu

RUN apt update
RUN apt install -y curl
RUN apt install -y jq

COPY download-frozen-image-v2.sh .
COPY archive.sh .

COPY bin/agent_secunet .

COPY ca.crt .
COPY nodeconfig_secunet.json nodeconfig.json

CMD ["./agent_secunet", "-v", "--broker=tls://mapi-dev.weeve.engineering:8883", "--heartbeat=100", "--loglevel=debug"]
