name: Test
on:
  push:
    branches:
      - cd/artifacts
jobs:
  build-and-push:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - uses: actions/checkout@v3
    - run: make build-all
    - uses: actions/upload-artifact@v3
      with:
        name: weeve-agent
        path: ./build/*